name: CREATE JIRA ISSUE

on:
  issues:
    types: [opened, edited]

jobs:
  jira:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

#      - name: Create
#        id: create
#        uses: atlassian/gajira-create@master
#        with:
#          project: SPD
#          issuetype: Technical Support
#          summary: |
#            Build completed for ${{ github.repository }}
#          description: |
#            Compare branch
#            fields: '{"customfield_10171": "test"}'

      - name: Log created JIRA issue
        run: echo "Issue ${{ secrets.JIRA_BASE_URL }} was created"
